export const colors = {
    LIGHTBLUE: "#D6F6FD",
    DEEPBLUE: "#0ACCF5",
    BACKGROUND_BLUE: "#F5FEFF",
    DELETE_BUTTON: "#FF0000",
    PLACEHOLDER: "#B9B9B9",
    GREY: "#646464",
    DARK_GREY: "#D4D4D4",
    DISABLED: "##3f3f3f",
    SUBJECT_LABEL: "#EEFF9E",
};
